name: "CI"

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-code:
    name: Test Code
    env:
      INTEGRATION_TEST_TOKEN: ${{ secrets.GCR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npx update-browserslist-db@latest
      - run: npm ci

  test-actions-delete-latest-n:
    name: Test action delete latest N packages
    runs-on: ubuntu-latest
    needs: [test-code]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Dummy Image - 0
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.dummy
          build-args: |
            RUN_NUMBER=${{ github.run_number }}-0
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghcr-delete-image-dummy:untagged

      - name: Build and Push Dummy Image - 1
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.dummy
          build-args: |
            RUN_NUMBER=${{ github.run_number }}-1
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghcr-delete-image-dummy:untagged

      - name: Build and Push Dummy Image - 2
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.dummy
          build-args: |
            RUN_NUMBER=${{ github.run_number }}-2
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghcr-delete-image-dummy:untagged

      - uses: ./
        with:
          owner: ${{ github.repository_owner }}
          name: ghcr-delete-image-dummy
          token: ${{ secrets.GCR_TOKEN }}
          untagged-keep-latest: 1

  test-actions-delete-by-tag:
    name: Test action delete by tag
    runs-on: ubuntu-latest
    needs: [test-code]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Dummy Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.dummy
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghcr-delete-image-dummy:${{ github.run_number }}

      - uses: ./
        with:
          owner: ${{ github.repository_owner }}
          name: ghcr-delete-image-dummy
          token: ${{ secrets.GCR_TOKEN }}
          tag: ${{ github.run_number }}
